repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
  -   id: debug-statements
  -   id: check-merge-conflict
  -   id: check-docstring-first
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  -   id: black
- repo: https://github.com/hukkinj1/mdformat
  rev: 0.7.1
  hooks:
  -   id: mdformat
      name: Format Markdown files
- repo: https://github.com/pycqa/bandit
  rev: 1.7.5
  hooks:
    - id: bandit
      args: [ --recursive, --skip, "B101,B701" ]
# - repo: https://github.com/codespell-project/codespell
#   rev: v2.2.6
#   hooks:
#     - id: codespell
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [ "--profile",  "black", "--line-length=72"]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
    - id: pyupgrade
      args: [ --py36-plus, ]
- repo: https://github.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  -   id: flake8
      additional_dependencies: ["flake8-bugbear==20.11.1", "pep8-naming==0.11.1"]
      args:
        - --max-line-length=150
        - --ignore=N806,N803
- repo: https://github.com/yunojuno/pre-commit-xenon
  rev: cc59b0431a5d072786b59430e9b342b2881064f6
  hooks:
    - id: xenon
      args: ["--max-average=A", "--max-modules=C", "--max-absolute=C"]
